name: Python CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Ersetze 'x' durch die gewünschte Python-Version

    - name: Install dependencies
      run: pip install flake8

    - name: Run code analysis
      run: flake8

